---
source:
  host: http://192.168.100.106/repo
  branch: exampleos/testing
  kernel_args:
    - root=LABEL=ROOT
    - rw
    - console=tty0
    - console=ttyS0,115200n8
disk:
  device: /dev/vda
  partitions:
    - name: EFI
      start: O%
      end: 256MB
      flags: [boot, esp]
    - name: ROOT
      start: 256MB
      end: 100%
  filesystems:
    - name: EFI
      label: EFI
      fs: vfat
      options: []
    - name: ROOT
      label: ROOT
      fs: ext4
      options: []
