name: debian-ostree-local-amd64
description: "Install Debian on amd64 via ostree remotes."
version: 0.1
type: ostree
architecture: amd64
params:
  disk: /dev/loop1
  repository: http://127.0.0.1/repo
  branch: pablo/${architecture}
stages:
  early:
  disk:
    - name: "Partitioning ${params.disk}."
      module: installer.disk.parted
      options:
        slices:
          - name: EFI
            start: 0%
            end: 256MB
            flags: [boot, esp]
          - name: ROOT
            start: 256MB
            end: 100%
            flags: []
    - name: "Formatting ${params.disk}."
      module: installer.disk.fs
      options:
        filesystems:
          - name: EFI
            label: EFI
            fs: vfat
            options: []
          - name: ROOT
            label: ROOT
            fs: ext4
            options: []
  unpack:
    - name: "Initiliazing repository."
      module: installer.ostree.init
      options: []
    - name: "Pulling from remote ostree branch"
      module: installer.ostree.pull.remote
      options: []
    - name: "Deploying branch"
      module: installer.ostree.deploy
      options:
        kernel_args:
          - root=LABEL=ROOT
          - rw
          - console=tty0
          - console=ttyS0,115200n8
  install:
    - name: "Install bootloader"
      module: installer.bootloader.ostree
      options: []
  post:
