---
source:
  origin: https://192.168.100.1/pablo.tar.gz
  file: rootfs.tar.gz
disk:
  device: /dev/vda
  partitiontype: gpt
  partitions:
    - name: EFI
      start: 0%
      end: 256MB
      flags: [boot, esp]
    - name: ROOT
      start: 256MB
      end: 100%
  filesystems:
    - name: EFI
      label: EFI
      fs: vfat
      options: []
    - name: ROOT
      label: ROOT
      fs: ext4
      options: []
kernel_args: "root=LABEL=ROOT console=tty0 console=ttyS0,115200"
