name: debian-amd64
description: "Install Debian on amd64."
version: 0.1
type: vanilla
architecture: amd64
params:
  disk: /dev/loop1
  source: pablo-installer-${version}-${architecture}.tar.gz
stages:
  early:
    - name: "Place holder."
      module: noop.placeholder
      options: []
  disk:
    - name: "Partitioning ${params.disk}."
      module: installer.disk.parted
      options:
        slices:
          - name: EFI
            start: 0%
            end: 256MB
            flags: [boot, esp]
          - name: ROOT
            start: 256MB
            end: 100%
            flags: []
    - name: "Formatting ${params.disk}."
      module: installer.disk.fs
      options:
        filesystems:
          - name: EFI
            label: EFI
            fs: vfat
            options: []
          - name: ROOT
            label: ROOT
            fs: ext4
            options: []
  unpack:
    - name: "Unpacking ${params.source}"
      module: installer.unpack
      options: []
  install:
    - name: "Installing bootloader on ${params.disk}"
      module: installer.bootloader
      options:
        kernel_args: "root=LABEL=ROOT console=tty0 console=ttyS0,115200"
  post:
