---
source:
  repository: /var/www/html/repo
  branch: pablo/1.0
disk:
  device: /dev/vda
  partitions:
    - name: EFI
      start: 0%
      end: 256MB
      flags: [boot, esp]
    - name: ROOT
      start: 256MB
      end: 100%
  filesystems:
    - name: EFI
      label: EFI
      fs: vfat
      options: []
    - name: ROOT
      label: ROOT
      fs: ext4
      options: []
