---
name: ExamplesOS-ostree
steps:
  - step: bootstrap
    options:
      suite: bookworm
      target: rootfs.tar.gz
      setup-hooks:
        - 'sync-in overlay/debian/ /'
      customize-hooks:
        - echo 'root:root' | chroot "$1" chpasswd
        - systemctl enable --root="$1" systemd-networkd
        - chroot $1 echo "localhost" > $1/etc/hostname
        - mkdir -p $1/efi
      packages: !include manifests/software.yaml
  - step: ostree_init
    options:
      repo: /var/www/html/repo
      mode: bare
  - step: ostree_prep
    options:
      repo: /var/www/html/repo
      branch: exampleos/testing
      target: rootfs.tar.gz
